apiVersion: apps/v1
kind: Deployment
metadata:
  name: microbot
spec:
  replicas: 3
  selector:
    matchLabels:
      role: microbot
  template:
    metadata:
      labels:
        role: microbot
    spec:
      containers:
      - name: microbot
        image: hub.docker.com/r/fr3nd/xeyes/
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080

